### ISSUE TITLE
Failed to fetch error

### ISSUE THREAD

**Issue by sbokman** [ClasicRando/web_rest_scraper#10]
I am trying to scrape this REST page: https://programs.iowadnr.gov/geospatial/rest/services/OneStop/QueryEnvFacs/MapServer/16
There are a lot of records, so it kept timing out. However now I'm getting a "Caught Error: TypeError: Failed to fetch" prompt.

Thank you!

**Comment by ClasicRando** [comment]
Hi Sarah,

In this case, the service is likely timing out the origin of the request (i.e. the GitHub page) since it's making too many requests simultaneously. It's not something I can deal with without possibly throttling the requests significantly when such an error occurs. This might work but would more than likely make such a scrape take days. I would suggest looking into the where clause feature (it utilizes the same where clause that the REST service does) and batch scrape by OID field, merging the resulting files into a single file if you need to have the data in 1 place.

**Comment by sbokman** [comment]
Thanks for taking a look Steven :)

I am not sure what all the clause feature or batch ID is, I'm not that savvy with the technical stuff lol.
I think I understand the concept, to collect the data in smaller bunches and then combine it all, but am not sure how to break up the data via REST page.
________________________________

**Comment by ClasicRando** [comment]
Not a problem, I'll try to provide guidance.

In the query page of the REST service, you have an option to provide a where clause that filters the data.
![image](https://user-images.githubusercontent.com/25016036/194652448-73b6c8f1-9dbd-453a-a0f6-2133f8918e9f.png)

With this in mind, you can provide it a range of uniqueID values with a where clause string of 'LOWER_BOUND <= uniqueID and uniqueID <= UPPER_BOUND' where your upper and lower bound values substituted in. This would allow you to get a batch then continue until you cannot get any more records. This will take a while though so keep in mind if they update data while you are mid batching you might get inconsistent data.

The other option is to wait for me to have time to add a batching feature to the page for services that support pagination so you can specify the batch sizes. The page would them collect a certain number of records, export the batch, then sleep for a set amount of time to avoid overloading the service. You still have the problem of collecting over a longer period of time (or possibly over multiple attempts/days) but I cannot see another way of getting around a server side error.

**Comment by sbokman** [comment]
I think I will wait for you to add the feature.
Once it's added, would I just leave the scraper open and running all day, even after I am off work?
________________________________

**Comment by ClasicRando** [comment]
Hi Sarah,

I have a pending change to the scraping process that allows me to scrape the service you referenced in the issue. This does mean the time to scrape will increase across the board and the output itself might change so you can review #11 for more details before I merge that branch to the main branch.

**Comment by sbokman** [comment]
Sweeeet thank you! So you are saying you were able to removed the duplicates?
And the output will in fact match the record count?
[cid:1ed47c90-07ad-400c-91f9-85910e69b59d]
________________________________

**Comment by ClasicRando** [comment]
It might match the feature count returned from the server but if the service contains duplicate features (again every detail including geometry and objectID must be the same) then those might be removed from the export if they are part of the same batch. I could make it so that duplicates are removed after batching to catch all duplicates (this would incur possible loses in performance) and note in the output the duplicate objectIDs but that would be something new and take more time.

**Comment by sbokman** [comment]
Oh nahh, that's unnecessary work. I would just make a note to the loader that there are duplicates :)
Thanks so much for your time on the scraper!!
________________________________

**Comment by ClasicRando** [comment]
All good with me. I reverted the distinct change so you will get every feature even if they are exactly the same. The change was pushed with #12. For this service the export might stress your system but I was able to collect that data (full feature count) in about 30 minutes. Hopefully this helps future scrapes
