### ISSUE TITLE
Getting stuck scraping page

### ISSUE THREAD

**Issue by sbokman** [ClasicRando/web_rest_scraper#22]
Hi, these 3 REST pages are getting stuck when trying to scrape.
The blue loading bar stops and never continues.
https://gisp.mcgi.state.mi.us/arcgis/rest/services/DEQ/Environmental_Mgt/MapServer/9
https://gisp.mcgi.state.mi.us/arcgis/rest/services/DEQ/Environmental_Mgt/MapServer/3
https://gisp.mcgi.state.mi.us/arcgis/rest/services/DEQ/Environmental_Mgt/MapServer/4
Thanks!

**Comment by ClasicRando** [comment]
Hi Sarah, this is a bug in the code in how it extracts geometry from a feature. I should be able to push a fix later today. However, just know that you will get back an actual geometry as Well Known Text since the geometry of the services is MultiPoint rather than a simple Point.
![Screenshot from 2023-03-08 14-37-20](https://user-images.githubusercontent.com/25016036/223825831-a789bac5-9353-46fa-8655-9e1c6204677e.png)
Note the `geometry` field and the values look like `MultiPoint(x y)`

**Comment by ClasicRando** [comment]
That change is live from #23. Let me know if you are able to scrape the source now

**Comment by sbokman** [comment]
It works! Thanks so much :)
Hope you are doing well!
________________________________

**Comment by ClasicRando** [comment]
Glad I could help!
